### PR TITLE
Issue 48

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
@gijzelaerr, is it right that the travis test still installs itself from the radio-astro PPA and not KERN?

**Comment by gijzelaerr** [comment]
jah could be, i didn't update it i think.

**Comment by o-smirnov** [comment]
@gijzelaerr could you check this please?

**Comment by gijzelaerr** [comment]
OK sure I can review things, and the changes dont look that huge. That said, i think it is a much more effective workflow to do peer reviews per item, not in big pile of changes in one PR. So please do one PR per issue, so I can actually verify if the problem is solved.

**Pull request merged**
