### PR TITLE
Updated code to remove or simulate the effects of the ionosphere on

### PR DESCRIPTION
**Pull request by twillis449**
Finally got around to implementing your advice re github as given back in your e-mail of April 25 2019.  I had to finally get going on learning about github pull requests as Benjamin Hugo wanted that done for the MeqTrees visualization stuff. :)

### CODE REVIEW

**Comment by o-smirnov** [comment]
Excellent, you'll grow to love it I'm sure!

May I suggest renaming the top-level TDL script? The name suggests the ionosphere itself is being rotated.

**Comment by bennahugo** [comment]
ok to test

**Comment by twillis449** [comment]
One might note that this piece of code is only designed to work with 'short' baselines where ionosphere rotation measure effects should be similar for all antennas in the array. Of course, exactly what 'short' means is open to various interpretations. :)

**Comment by bennahugo** [comment]
Good to know. I missed this PR and am now re-initializing our build server. So will merge when it passes. Hope you are well @twillis449

**Comment by bennahugo** [comment]
retest this please

**Pull request merged**
