### PR TITLE
try out makems from LOFAR

### PR DESCRIPTION
**Pull request by gijzelaerr**

### CODE REVIEW

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
Looks like a bug in the latest casacore:
```
creating new column BITFLAG_ROW using an IncrementalStMan storage manager
DATA column storage manager type is StandardStMan
BITFLAG column will use a default storage manager
Adding BITFLAG column with fixed shape: [4, 64]
2018/05/29 08:07:45 ABORT: /usr/local/bin/addbitflagcol returned error code -11
2018/05/29 08:07:45 ERROR: exiting with error code 1, check the logs for errors
2018/05/29 08:07:45 INFO: elapsed time is 0h0m1.26s
========== Removing files
========== $ rm -fr WSRT.MS* WSRT*img WSRT*fits
========== Running makems
========== $ makems /code/test/Batchtest/WSRT_makems.cfg
========== $ mv WSRT.MS_p0 WSRT.MS
========== $ pyxis WSRT.MS ms.prep
Traceback (most recent call last):
  File "batch_test.py", line 92, in <module>
    run("pyxis WSRT.MS ms.prep"); #TODO: this is hacky, bug in CASAcore
  File "batch_test.py", line 30, in run
    raise RuntimeError,"failed with exit code %x"%code;
RuntimeError: failed with exit code 1
```

**Comment by bennahugo** [comment]
Its addColumn that is segfaulting
```
#0  0x00007ffff72a138a in casa::SSMBase::removeColumn(casa::DataManagerColumn*) () from /usr/lib/x86_64-linux-gnu/libcasa_tables.so.2
#1  0x00007ffff7194901 in casa::ColumnSet::doAddColumn(casa::ColumnDesc const&, casa::DataManager*) ()
   from /usr/lib/x86_64-linux-gnu/libcasa_tables.so.2
#2  0x00007ffff7196f49 in casa::ColumnSet::addColumn(casa::ColumnDesc const&, bool, casa::TSMOption const&, casa::Table&) ()
   from /usr/lib/x86_64-linux-gnu/libcasa_tables.so.2
#3  0x00007ffff71b6f4a in casa::PlainTable::addColumn(casa::ColumnDesc const&, bool) ()
   from /usr/lib/x86_64-linux-gnu/libcasa_tables.so.2
#4  0x000055555555948b in main ()
```

**Comment by gijzelaerr** [comment]
can't replicate the problem with the KERN package of meqtrees, maybe it is MS specific
```
$  /usr/bin/addbitflagcol meerkat_0h10s.MS 
creating new column BITFLAG_ROW using an IncrementalStMan storage manager
DATA column storage manager type is TiledShapeStMan
BITFLAG column will use a default storage manager
Adding BITFLAG column with variable shape
Initializing variable-shaped BITFLAG column
$  dpkg -S /usr/bin/addbitflagcol
meqtrees-timba: /usr/bin/addbitflagcol
$  apt-cache show meqtrees-timba:
Package: meqtrees-timba
Priority: extra
Section: science
Installed-Size: 408
Maintainer: KERN packaging <packaging@kernsuite.info>
Architecture: amd64
Version: 1.5.1-1kern1
Depends: libc6 (>= 2.14), libcasa-casa2, libcasa-images2, libcasa-measures2, libcasa-ms2, libcasa-msfits2, libcasa-tables2, libcfitsio5 (>= 3.390~), libfftw3-double3 (>= 3.3.5), libgcc1 (>= 1:3.0), libstdc++6 (>= 5.2), libwcs5 (>= 4.8.2), python-meqtrees-timba, libmeqtrees-timba0, casarest, python2.7
Filename: pool/main/m/meqtrees-timba/meqtrees-timba_1.5.1-1kern1_amd64.deb
Size: 100424
MD5sum: 995af5815755242ee3c0a93bfd9ab994
SHA1: a322ae70d1c61e3bdeeaae45838c4fab747b8370
SHA256: 1296c57543e31ff3edc65c624840e741ef5ec82aef38c2d38fff81901276cb89
Description-en: implementing and solving arbitrary Measurement Equations
 MeqTrees is a software package for implementing Measurement Equations. This
 makes it uniquely suited for simulation and calibration of radioastronomical
 data, especially that involving new radiotelescopes and observational
 regimes.
 .
 MeqTrees includes a highly capable FITS viewer and sky model manager called
 Tigger, which can also work as a standalone tool.
Description-md5: 72e294c70ac8c86e7edccfb79c0b1b96

$  cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

**Comment by bennahugo** [comment]
linkage looks okay:
```
root@6a5b7c27dc5d:/code/test/Batchtest# ldd /usr/lib/x86_64-linux-gnu/libcasa_tables.so.2
        linux-vdso.so.1 (0x00007ffec51f2000)
        libcasa_casa.so.2 => /usr/lib/x86_64-linux-gnu/libcasa_casa.so.2 (0x00007faa04565000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007faa041d7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007faa03e39000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007faa03c21000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007faa03a02000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faa03611000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007faa0340d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007faa0539a000)
```

**Comment by bennahugo** [comment]
maybe it is lofar's makems that is the problem

**Comment by gijzelaerr** [comment]
maybe time to switch to writems

**Comment by bennahugo** [comment]
The segfault is in the latest casacore (master).. will try and reproduce with latest release to double check

**Comment by bennahugo** [comment]
also there in CC 2.4.0. I can only conclude it it is a LOFAR makems problem

**Comment by bennahugo** [comment]
@gijzelaerr can you elaborate on what is wrong  with the makems build?

**Comment by gijzelaerr** [comment]
https://github.com/kernsuite/packaging/issues/103
https://github.com/ska-sa/makems/issues/3

I prefer to ditch it completely. Can you switch the writems which is now part of casacore?

**Comment by gijzelaerr** [comment]
otherwise, @Athanaseus could try to fix the upstream makems pacakge and role a new debian package for  kern-dev (4)

**Comment by gijzelaerr** [comment]
superseded by recent work

**Pull request closed without merging**
