### PR TITLE
It's that time again, merging all the new features and bugfixes from devel into master for a new release

### PR DESCRIPTION
**Pull request by o-smirnov**

### CODE REVIEW

**Comment by o-smirnov** [comment]
Looks like the checks are failing due to the test scripts being out of date (package names etc.) @gijzelaerr what do you think?

**Comment by gijzelaerr** [comment]
I think somebody has been developing on this branch for years without checking the build status. 

Trying to fix this now.

**Comment by gijzelaerr** [comment]
ok it is almost working, not sure yet why travis can't find kittens, can't replicate the problem with docker.

When I run it i get this error:

```
========= Removing files
========== $ rm -fr WSRT.MS* WSRT*img WSRT*fits
========== Running makems
========== $ makems /meqtrees-cattery/test/Batchtest/WSRT_makems.cfg
Debug: registered context Global=0
Debug::loadLevels: error opening makems.debug
Created 1 MS part and its VDS file
Created global VDS file WSRT.MS.gds
========== $ mv WSRT.MS_p0 WSRT.MS
========== $ ls -ld WSRT.MS
drwxr-xr-x 14 root root 4096 Jan  8 12:08 WSRT.MS
========== $ /usr/bin/owlcat.sh downweigh-redundant-baselines WSRT.MS
Successful read/write open of default-locked table WSRT.MS: 22 columns, 7560 rows
Successful readonly open of default-locked table /meqtrees-cattery/test/Batchtest/WSRT.MS/ANTENNA: 8 columns, 14 rows
00:00:00: Looking for redundant baselines
105 baselines
Baseline 0m, 14 ifrs: 0-0 1-1 2-2 3-3 4-4 5-5 6-6 7-7 8-8 9-9 10-10 11-11 12-12 13-13
Baseline 72m, 2 ifrs: 10-11 12-13
Baseline 144m, 9 ifrs: 0-1 1-2 2-3 3-4 4-5 5-6 6-7 7-8 8-9
Baseline 288m, 8 ifrs: 0-2 1-3 2-4 3-5 4-6 5-7 6-8 7-9
Baseline 432m, 7 ifrs: 0-3 1-4 2-5 3-6 4-7 5-8 6-9
Baseline 576m, 6 ifrs: 0-4 1-5 2-6 3-7 4-8 5-9
Baseline 720m, 5 ifrs: 0-5 1-6 2-7 3-8 4-9
Baseline 864m, 4 ifrs: 0-6 1-7 2-8 3-9
Baseline 1008m, 3 ifrs: 0-7 1-8 2-9
Baseline 1152m, 2 ifrs: 0-8 1-9
Baseline 1296m, 3 ifrs: 0-9 10-12 11-13
Baseline 1332m, 2 ifrs: 0-10 9-12
Baseline 1404m, 2 ifrs: 0-11 9-13
00:00:00: Closing MS.
========== $ lwimager1.2 ms=WSRT.MS data=CORRECTED_DATA mode=channel weight=natural npix=10
/bin/sh: 1: lwimager1.2: not found
Traceback (most recent call last):
  File "batch_test.py", line 92, in <module>
    run("lwimager1.2 ms=WSRT.MS data=CORRECTED_DATA mode=channel weight=natural npix=10");
  File "batch_test.py", line 29, in run
    raise RuntimeError,"failed with exit code %x"%code;
RuntimeError: failed with exit code 7f
```

Oleg we gave up the lwimager1.2 package a long time ago, what should happen?

**Comment by o-smirnov** [comment]
Pushed some changes. Batch_test works on my laptop at least/

**Pull request merged**
